### ISSUE TITLE
RuntimeError while training

### ISSUE THREAD

**Issue by Kautenja** [CYang0515/pytorch_ssn#3]
A run time error occurs when running the training script:

```
python3 train.py --root_dir ../ssn_superpixels/data
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
(63,)
(64,)
epoch:0, iter:0, total_loss:0.46526679396629333, pos_loss:0.3472626507282257, rec_loss:0.11800415068864822
forward time:10.672, backward time:24.413, total time:35.085
epoch:0, iter:1, total_loss:0.4646613299846649, pos_loss:0.33802738785743713, rec_loss:0.12663394212722778
forward time:8.234, backward time:23.582, total time:31.829
epoch:0, iter:2, total_loss:0.5269129276275635, pos_loss:0.39734792709350586, rec_loss:0.12956497073173523
forward time:8.337, backward time:23.679, total time:32.030
epoch:0, iter:3, total_loss:0.6377366781234741, pos_loss:0.35707888007164, rec_loss:0.2806577980518341
forward time:8.041, backward time:23.849, total time:31.904
epoch:0, iter:4, total_loss:0.5072599649429321, pos_loss:0.3666442334651947, rec_loss:0.14061571657657623
forward time:7.918, backward time:23.623, total time:31.554
epoch:0, iter:5, total_loss:0.4929073452949524, pos_loss:0.35064756870269775, rec_loss:0.14225976169109344
forward time:7.664, backward time:23.973, total time:31.650
epoch:0, iter:6, total_loss:0.7047260999679565, pos_loss:0.41431793570518494, rec_loss:0.2904081344604492
forward time:7.722, backward time:23.757, total time:31.491
epoch:0, iter:7, total_loss:0.4532756805419922, pos_loss:0.3590615689754486, rec_loss:0.09421411901712418
forward time:7.631, backward time:23.410, total time:31.053
epoch:0, iter:8, total_loss:0.45245760679244995, pos_loss:0.34370195865631104, rec_loss:0.10875564813613892
forward time:7.728, backward time:23.157, total time:30.897
epoch:0, iter:9, total_loss:0.5186131596565247, pos_loss:0.3774457573890686, rec_loss:0.14116740226745605
forward time:7.695, backward time:23.133, total time:30.840
epoch:0, iter:10, total_loss:0.5209752321243286, pos_loss:0.39270031452178955, rec_loss:0.12827493250370026
forward time:7.789, backward time:23.179, total time:30.982
epoch:0, iter:11, total_loss:0.54443359375, pos_loss:0.40878820419311523, rec_loss:0.13564535975456238
forward time:7.725, backward time:23.341, total time:31.080
epoch:0, iter:12, total_loss:0.48685306310653687, pos_loss:0.35385414958000183, rec_loss:0.13299889862537384
forward time:3.468, backward time:11.316, total time:14.798
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/bitcommander/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py:611: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main()
  File "train.py", line 115, in main
    train_net(var_args, writer)
  File "train.py", line 71, in train_net
    recon_feat2, recon_label = model(img, p2sp_index_, invisible, init_index, cir_index, problabel, num_h, num_w, device)
  File "/home/bitcommander/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bitcommander/Documents/dissertation/superpixel-sampling/reference/pytorch_ssn/model.py", line 105, in forward
    self.num_spixels_h, self.num_spixels_w, self.num_spixels, 50)
  File "/home/bitcommander/Documents/dissertation/superpixel-sampling/reference/pytorch_ssn/util.py", line 299, in decode_features
    img_concat_spixel_feat = img_concat_spixel_feat.permute(0, 1, 4, 2, 3).reshape(b, -1, h, w)
  File "/usr/lib/python3.7/traceback.py", line 193, in format_stack
    def format_stack(f=None, limit=None):
  File "/home/bitcommander/.local/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 11576) is killed by signal: Killed. 
```

**Comment by Kautenja** [comment]
this is in CPU mode

**Comment by Kautenja** [comment]
I'm thinking this is just a memory error.
