### ISSUE TITLE
a question when running test.py on model.py, SpixelFeature()

### ISSUE THREAD

**Issue by forrestsz** [CYang0515/pytorch_ssn#5]
Hi, thank you for your implementation, which is very helpful.
I want to see the ssn superpixels, so i am trying to run the test.py.
But i meet some mistake as following, and I am no understand what are doing here.

```
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\windows\pytorch\aten\src\ATen/native/IndexingUtils.h:20)
Traceback (most recent call last):
  File "C:/Users/wujunxian/Desktop/qh/pytorch_ssn-master/test.py", line 102, in <module>
    var_args.pre_dir, var_args.result_dir)
  File "C:/Users/wujunxian/Desktop/qh/pytorch_ssn-master/test.py", line 54, in compute_spixels
    num_w, device)
  File "C:\Users\wujunxian\Anaconda3\envs\qh\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\wujunxian\Anaconda3\envs\qh\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\wujunxian\Anaconda3\envs\qh\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\wujunxian\Desktop\qh\pytorch_ssn-master\model.py", line 88, in forward
    spixel_feature = SpixelFeature(trans_features, init_index, max_spixels=self.num_spixels)
  File "C:\Users\wujunxian\Desktop\qh\pytorch_ssn-master\util.py", line 70, in SpixelFeature
    feat = feat[:, :, init_y[0], init_x[0]]  #B*C*n
IndexError: The shape of the mask [161376] at index 0 does not match the shape of the indexed tensor [1, 5, 328, 492] at index 2
```

The function SpixelFeature as show
```python
def SpixelFeature(feat, init_index, max_spixels=50, invisible_p=None):
    """
    init superpixel feature
    :param feat:  inputs feature of shape （B,C,H,W)
    :param init_index:   each spixel with corresponding pixel coordinates
    :param type: feature merge style default average
    :param max_spixels:  superpixel numbers
    :param ignore_id:
    :param rgb_scale:
    :param ignore_feat: 0
    :param invisible_p: ignore pixel of shape (B,H,W)
    :return: ave_feat: project pixel to superpixel feature; back_ave_feat: project superpixel to pixel feature
    """
    b, c, h, w = feat.shape
    init_x, init_y, init_l = init_index  #B*n  B*n  B*D  n=D*init_l[0,0]
    # Here, i transform the datatype to uint8, otherwise will happen IndexError: tensors used as indices must be long, byte or bool tensors
    init_x, init_y, init_l = init_x.byte(), init_y.byte(), init_l.byte() 
    if len(init_x.shape) ==1:
        init_x = torch.from_numpy(init_x).unsqueeze(0)
        init_y = torch.from_numpy(init_y).unsqueeze(0)
        init_l = torch.from_numpy(init_l).unsqueeze(0)

    # happen some error in here
    feat = feat[:, :, init_y[0], init_x[0]]  #B*C*n
    feat = feat.reshape(b, c, max_spixels, init_l[0, 0])
    # add ignore regions
    if invisible_p is not None:
        inv = invisible_p[:, init_y[0], init_x[0]]
        inv = inv.reshape(b, 1, max_spixels, init_l[0, 0])
        feat = (feat * (1 - inv)).sum(dim=3)
        valid = (1 - inv).sum(dim=3)
        ave_feat = feat / (valid + 1e-5)
    else:
        ave_feat = feat.sum(dim=3) / init_l[0, 0].float()

    return ave_feat
```

and I can show you the shape of each variable in debug.
`feat` is 1x5x328x492,
`init_x` is 1x161376,
`init_y` is 1x161376
`init_l` is 1x96
`init_l[0,0]` is 145
`max_spixels` is 96

Great thank for you!

**Comment by CYang0515** [comment]
I guess, when you convert the type of {init_x} to byte, the index become the bool index. There need a matrix index to aggregate pixel feature. You can use tensor.long() to replace tensor.byte().

**Comment by forrestsz** [comment]
I try, It work! great thank for you!
