### ISSUE TITLE
Error in runtime execution

### ISSUE THREAD

**Issue by higornucci** [CYang0515/pytorch_ssn#7]
Hi.

I am getting the following error after run the train.py in the BSR dataset

```
Python 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)] on win32
runfile('D:/projetos/pytorch_ssn/train.py', wdir='D:/projetos/pytorch_ssn')
(70,)
(58,)
(52,)
Traceback (most recent call last):
  File "C:\Users\higor\anaconda3\envs\pytorch-covid\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6ad1003877de>", line 1, in <module>
    runfile('D:/projetos/pytorch_ssn/train.py', wdir='D:/projetos/pytorch_ssn')
  File "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/projetos/pytorch_ssn/train.py", line 118, in <module>
    main()
  File "D:/projetos/pytorch_ssn/train.py", line 114, in main
    train_net(var_args, writer)
  File "D:/projetos/pytorch_ssn/train.py", line 77, in train_net
    recon_feat2, recon_label = model(img, p2sp_index_, invisible, init_index, cir_index, problabel,
  File "C:\Users\higor\anaconda3\envs\pytorch-covid\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\higor\anaconda3\envs\pytorch-covid\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\higor\anaconda3\envs\pytorch-covid\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\projetos\pytorch_ssn\model.py", line 88, in forward
    spixel_feature = SpixelFeature(trans_features, init_index, max_spixels=self.num_spixels)
  File "D:\projetos\pytorch_ssn\util.py", line 71, in SpixelFeature
    feat = feat[:, :, init_y[0], init_x[0]]  # B*C*n
IndexError: tensors used as indices must be long, byte or bool tensors
```

Do you guys have any idea where the error may be? (i didnt change the code)

**Comment by CYang0515** [comment]
May be the index data type is incompatible in different pytorch version. You can check the **init_y** data type.

**Comment by higornucci** [comment]
I changed the data **init_y** data type in the **util.py** and it worked. Thank you. 

`line 66 init_x, init_y, init_l = init_x.long(), init_y.long(), init_l.long()`
